### PR TITLE
added question3

### PR DESCRIPTION
**Pull request by shrey141102**
Submitting this Pull Request for my issue #4 .
Please accept the changes

### CODE REVIEW

**Comment by Anjalijha12345** [comment]
@shrey141102 Update the readme

**Comment by shrey141102** [comment]
@Anjalijha12345 done
please check

**Comment by shrey141102** [comment]
Add label also for hacktoberfest please

**Comment by Anjalijha12345** [comment]
@shrey141102 you can contribute in this profile too https://github.com/diwakar1593

**Comment by shrey141102** [comment]
okayy

**Comment by shrey141102** [comment]
@Anjalijha12345 can you add a label `hacktoberfest-accepted`
i think thats mandatory

**Pull request merged**
